version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: app
    hostname: app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - my-network

  mongo:
    image: mongo:latest
    container_name: "mongodb"
    command: ["--bind_ip_all"]
    ports:
      - 27017:27017
    networks:
      - my-network
    volumes:
      - ./api:/usr/app/
      - /usr/app/node_modules
    restart: on-failure

networks:
  my-network:
    driver: bridge