micronaut:
  application:
    name: challenge-meli
  context-path: challenge

pais-ip:
  path: "https://api.ip2country.info"

info-pais:
  path: "https://restcountries.eu/rest/v2"

tarifa-pais:
  path: "http://data.fixer.io/api"
  api-key: "c9376a676d97684d4a2f286060ef33ad"

mongodb:
  database: "challenge"
  collection: "listaip"
  uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}"